# final String configFile = "fbmidibridge-1746b45f5da7.json";  // arg2
# final String databaseName = "fbmidibridge"; // arg1
# final String pathToListenForEventsIn = "testchannel"; // arg3
# final String midiDeviceName = "toReason"; // arg4

firebaseDatabaseConfig:
    configFile: fbmidibridge-1746b45f5da7.json
    databaseName: fbmidibridge


midiDestinations:
   - id:  toReason
     midiDeviceName: toReason

firebaseDestinations:
    - id: testchannel
      path: testchannel


midiRoutes:
    - source: testchannel
      destination: toReason

#  XXX So far not setting up routing for web input.  Need to look into that a bit.
#      probably use the same framework as for firebase/midi.